name: Build with Maven
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .version file
        id: version
        run: echo "version=$(cat .github/.version)" >> $GITHUB_OUTPUT
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Build with Maven
        run: |
          sed -i "s|0.0.0|"$(cat .github/.version)"|g" pom.xml
          mvn -B package --file pom.xml
          rm -rf target/original-*.jar
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            target/ram.jar
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          version-type: release
          github-prerelease: false
          name: v${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          github-tag: v${{ steps.version.outputs.version }}
#          java: 17
#          loaders: 
#          game-versions: 
          modrinth-id: 5QQHU3Yt
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
#          curseforge-id: 394468
#          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
