name: Build with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .version file
      id: version
      run: echo "version=$(cat .github/.version)" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto

    - name: Build with Maven
      run: | 
       sed -i "s|0.0.0|"$(cat .github/.version)"|g" pom.xml
       mvn -B package --file pom.xml
       rm -rf target/original-*.jar

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/ram.jar

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.event_name != 'pull_request'
      with:
        prerelease: false
        repo_token: ${{ github.token }}
        title: v${{ steps.version.outputs.version }}
        automatic_release_tag: v${{ steps.version.outputs.version }}
        files: |
          target/ram.jar
