name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .version file
      id: version
      run: echo "::set-output name=version::$(cat .github/.version)"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: | 
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' pom.xml
       grep pom.xml -e ${{ steps.version.outputs.version }}
       mvn -B package --file pom.xml
       rm -rf target/original-*.jar

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/ram.jar
